### ISSUE TITLE
New MFE: Learner Record

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/frontend-app-learner-record#107]
### Product scope and feature details

- What's included?

Everything in the Credentials UI except rendering of certs themselves which remains with the IDA.

- What features does this new MFE deprecate?

Masquerading --> Replaced by a tab in the Support Tools MFE (see [Olive Release notes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3396501578/Olive) for now but we are also adding an ADR to the MFE itself to explain this choice)

### Community Release Information

**Product-ready details:**

- Is this feature enabled by default? Is it currently enabled?
Off by default

- Is this feature internationalized?
I believe so and if not we need a checklist for what's missing.

- Is this feature theme-able?
yes

- What's the production status as of the date of the code cut-off? 
Beta/experimental

- Primary contact: https://github.com/orgs/openedx/teams/2u-aperture

**Documentation details:**

- Link to Product blog:
- Link to "How to enable": This should be covered by [the README](https://github.com/openedx/frontend-app-learner-record/blob/master/README.rst) now.
- Link to any other relevant technical documentation: See README

### Child Tasks

- [x] #108
- [x] https://github.com/openedx/frontend-app-learner-record/issues/97
- [x] ~https://github.com/openedx/frontend-app-learner-record/issues/102~

### PRs

- [x] https://github.com/overhangio/tutor-credentials/pull/17

**Comment by arbrandes** [comment]
Tutor can't support this until the credentials backend is also supported.  Blocked.

**Comment by arbrandes** [comment]
Great news: https://github.com/overhangio/tutor-credentials is official and supported, so we can work on including Learner Record in Tutor officially!
